# Generated by Django 4.1.2 on 2023-01-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='buy/static/images'),
        ),
    ]
