# Generated by Django 4.1.2 on 2023-01-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='buy/images'),
        ),
    ]
